name: Shrine
description: A new Flutter application.
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional bubuild number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  #flutter_localizations:
    #sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_exif_rotation: ^0.2.7
  validate: ^1.7.0
  intl: ^0.15.6
  #flutter_html_view: "^0.3.1"
  permission_handler: ^3.1.0
  location: ^2.3.5
  geocoder: ^0.2.1
  dio: ^1.0.6
  json_annotation: ^0.2.3
  shared_preferences: ^0.4.2
  image_picker: 0.6.1+8
  image: ^2.1.4
  flutter_launcher_icons: "^0.6.1"
  datetime_picker_formfield: ^0.4.2
  barcode_scan: ^1.0.0
  url_launcher: ^5.1.3
  charts_flutter: ^0.4.0
  splashscreen: ^1.1.0
  share: ^0.5.3
  launch_review: ^1.0.1
  native_device_orientation: ^0.0.3
  connectivity: ^0.3.2
  exifdart: ^0.7.0+2
  #flutter_image_compress: ^0.2.2
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  csv: ^4.0.3
  pdf: ^1.3.10
  simple_share:
  #simple_permissions: ^0.1.9
  sqflite: ^1.1.0
  #shashank
  android_intent: ^0.3.2
  geolocator: ^5.1.2
  native_contact_picker: ^0.0.6
  camera: ^0.5.6+3
  path_provider: ^1.5.1
  path:
  flutter_image_compress: 0.6.3
  photo_view: 0.6.0
  image_gallery_saver: 1.2.2
  firebase_dynamic_links: 0.5.0+6
  firebase_core: ^0.4.0+9
  easy_dialog: ^1.0.5
  http: 0.12.0+2
  dependencies:
  firebase_auth: ^0.11.1+6
  cloud_firestore: ^0.12.5
  firebase_messaging: 5.1.6
  flutter_local_notifications:
  rounded_modal: ^1.0.0
  admob_flutter: 0.3.4
  device_info: 0.4.2+1
  rxdart: ^0.23.1
  #video_player: ^0.10.5
  wakelock: ^0.1.3+3
  flutter_keyboard_visibility: ^0.7.0
  firebase_ml_vision: ^0.6.0+2
  screen: 0.0.5
  audioplayers: 0.15.1
  flutter_background_geolocation: 1.7.0
  latlong: 0.6.1
  unicorndial: 1.1.5
  flutter_map: 0.8.2
  firebase_database: 3.1.3
  google_maps_flutter: ^0.5.11+1
  flutter_polyline_points: ^0.1.0
  rflutter_alert: ^1.0.3
  #path_provider_macos: 0.0.4+3



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  android: true
  image_path: "assets/launch_logo.png"
  image_path_android: "assets/launch_logo.png"
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/diamond.png
      - assets/logo.png
      - assets/spinner.gif
      - assets/splash.gif
      - assets/launch_logo.png
      - assets/landing.png
      - assets/qr.png
      - assets/avatar.png
      - assets/add_admin.png
      - assets/mark_attendance.png
      - assets/reqtimeoff.png
      - assets/att_log.png
      - assets/visitlog.png
      - assets/changepwd.png
      - assets/editprofile.png
      - assets/attreport.png
      - assets/config.png
      - assets/addemp.png
      - assets/timeofflog.png
      - assets/empvisit.png
      - assets/imgloader.gif
      - assets/icons8-offline-100.png
      - assets/Beep_Short.mp3
      - assets/facerecog.png
      - assets/icons8-camera-50.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family:  CustomIcon
      fonts:
        - asset: fonts/Custom.ttf